FROM openjdk:11-jre-slim
COPY target/data-management-service-0.0.1-SNAPSHOT.jar /home/data-management-service-0.0.1-SNAPSHOT.jar
EXPOSE 8802
CMD ["java","-jar","/home/data-management-service-0.0.1-SNAPSHOT.jar"]